// Generated by CoffeeScript 1.7.1
(function() {
  var db, file_location, fs, lookup, sqlite3;

  file_location = './measuredincm.db';

  fs = require('fs');

  sqlite3 = require('sqlite3').verbose();

  db = new sqlite3.Database(file_location);

  lookup = function() {
    var results, stmt;
    fs.exists(file_location, function(exists) {
      if (exists) {
        return console.log('this file exists.');
      }
    });
    stmt = 'SELECT * FROM track_history LIMIT 5';
    return results = db.all(stmt, function(err, rows) {
      return rows;
    });
  };

  exports.lookup = lookup;

}).call(this);
